# Generated by Django 4.2.4 on 2023-08-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_view_count',
        ),
    ]
